from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.sql import func

from app.database.database import Base


class User(Base):
    """
    ResearchMate application user.

    Passwords are never stored in plaintext; password_hash contains the
    PBKDF2-derived value generated by app.core.auth.hash_password.
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)

    name = Column(
        String(120),
        nullable=False,
    )

    email = Column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )

    password_hash = Column(
        String(255),
        nullable=False,
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
