import React, {useEffect, useState} from "react";
import {CalendarDays, ExternalLink, Search, ShieldCheck} from "lucide-react";
const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8001";
export default function ConferencePage(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[category,setCategory]=useState("All"),[categories,setCategories]=useState([]),[error,setError]=useState("");
 const load=async()=>{try{const u=new URL(`${API}/conferences`); if(q)u.searchParams.set("query",q);if(category!=="All")u.searchParams.set("category",category);const r=await fetch(u);if(!r.ok)throw Error("Conference service unavailable");setItems(await r.json());}catch(e){setError(e.message)}};
 useEffect(()=>{fetch(`${API}/conferences/categories`).then(r=>r.json()).then(setCategories).catch(()=>{});},[]); useEffect(()=>{load()},[category]);
 return <div style={{maxWidth:1500,margin:"0 auto"}}><div style={{padding:"28px",borderRadius:24,background:"linear-gradient(135deg,#f5fffb,#f5f8ff)",border:"1px solid #e3e9ef",marginBottom:20}}><div style={{fontSize:12,fontWeight:800,letterSpacing:2,color:"#16855b"}}>CONFERENCE INTELLIGENCE</div><h1 style={{fontSize:40,margin:"8px 0"}}>Discover research opportunities</h1><p style={{color:"#66788a",maxWidth:760}}>Find conferences by research area and inspect verified source information. Dates are never invented; unverified fields are explicitly marked.</p><div style={{display:"flex",gap:10,marginTop:18}}><div style={{display:"flex",alignItems:"center",gap:8,background:"white",padding:"10px 12px",borderRadius:10,flex:1}}><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search conference or research scope" style={{border:0,outline:0,width:"100%"}}/></div><select value={category} onChange={e=>setCategory(e.target.value)} style={{padding:10,borderRadius:10,border:"1px solid #dfe5ec"}}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button onClick={load} style={{border:0,borderRadius:10,padding:"0 18px",background:"#16855b",color:"white",fontWeight:700}}>Search</button></div></div>{error&&<div style={{padding:14,background:"#fff1f1",borderRadius:10,color:"#b42318",marginBottom:16}}>{error}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:16}}>{items.map(c=><article key={c.id} style={{background:"white",border:"1px solid #e5eaf0",borderRadius:18,padding:20,boxShadow:"0 4px 18px rgba(20,35,50,.04)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><span style={{fontSize:11,fontWeight:800,padding:"5px 8px",borderRadius:20,background:"#edf7f2",color:"#16855b"}}>{c.category}</span><span style={{fontSize:11,color:c.verification_status==="verified"?"#16855b":"#b7791f"}}><ShieldCheck size={13} style={{verticalAlign:"middle"}}/> {c.verification_status}</span></div><h2 style={{fontSize:20}}>{c.name}</h2><p style={{color:"#68788a"}}>{c.scope||"Scope information not provided."}</p><div style={{fontSize:13,color:"#536476",display:"grid",gap:7}}><div><CalendarDays size={14}/> Paper deadline: {c.paper_deadline?new Date(c.paper_deadline).toLocaleDateString():"Not verified"}</div><div>Conference date: {c.conference_date?new Date(c.conference_date).toLocaleDateString():"Not verified"}</div><div>{c.location||"Location not specified"} · {c.mode||"Mode not specified"}</div></div>{c.source_url&&<a href={c.source_url} target="_blank" rel="noreferrer" style={{display:"inline-flex",gap:6,marginTop:14,color:"#2877d5"}}>Source <ExternalLink size={14}/></a>}</article>)}</div>{!items.length&&!error&&<div style={{padding:50,textAlign:"center",color:"#68788a"}}>No sourced conference records yet. Add verified records through the Conference API.</div>}</div>
}
