import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, NavLink, Routes, Route, useNavigate, useParams} from 'react-router-dom';
import * as I from 'lucide-react';
import './index.css';

const modules = [
  {id:'discovery', label:'Research Discovery', icon:'Compass', color:'teal', desc:'Validate your idea, uncover gaps and shape a research direction.', steps:['Topic Validation & Novelty','Research Gap Finder','Research Questions & Hypothesis','Feasibility Analysis','Dataset Recommendation']},
  {id:'literature', label:'Literature Intelligence', icon:'BookOpen', color:'blue', desc:'Find, understand and compare the literature behind your research.', steps:['Semantic Literature Search','Paper / PDF Analysis','Literature Summarizer','Literature Matrix','Citation Recommendations']},
  {id:'writing', label:'Research Writing', icon:'PenLine', color:'violet', desc:'Build a stronger academic manuscript with context-aware writing tools.', steps:['Paper Structure','Title & Abstract Optimizer','Academic Writing Assistant','Citation & Reference Checker','Formatting Checker']},
  {id:'originality', label:'Originality & Citations', icon:'ShieldCheck', color:'amber', desc:'Check similarity, plagiarism risk and citation quality before submission.', steps:['Similarity Analysis','Plagiarism-Risk Prediction','Matched Sources','Citation Integrity','Risky Passage Detection']},
  {id:'review', label:'AI Review & Improvement', icon:'MessageSquareText', color:'rose', desc:'Simulate peer review, understand feedback and prioritize revisions.', steps:['AI Reviewer','Reviewer Comment Explainer','Response-to-Reviewer','Paper Improvement Planner','Acceptance-Risk Analysis']},
  {id:'publication', label:'Publication Assistant', icon:'Rocket', color:'green', desc:'Find trustworthy venues and manage the path from draft to publication.', steps:['Journal Recommendation','Conference Recommendation','Predatory Journal Detection','Submission Checklist','Deadline & CFP Tracker']}
];

const project = {name:'Explainable AI for Rural Healthcare Diagnosis', stage:'Literature & Methodology', progress:68, papers:42, novelty:84, readiness:72, deadline:'30 days'};
function Icon({n,s=18}) { const C=I[n]||I.Circle; return <C size={s} strokeWidth={1.9}/> }
function Button({children,variant='primary',...p}) { return <button className={variant==='primary'?'primary':'secondary'} {...p}>{children}</button> }
function Layout({children}) {
 const [mobile,setMobile]=useState(false);
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?'mobile-open':''}`}>
   <div className="brand"><div className="brand-mark"><I.Brain size={22}/></div><div><div className="brand-name">ResearchMate <span>AI</span></div><div className="brand-sub">Research publication assistant</div></div></div>
   <div className="workspace-label">WORKSPACE</div>
   <nav>{<NavLink to="/" end onClick={()=>setMobile(false)} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon n="LayoutDashboard"/><span>Dashboard</span></NavLink>}
   {modules.map(m=><NavLink key={m.id} to={`/module/${m.id}`} onClick={()=>setMobile(false)} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon n={m.icon}/><span>{m.label}</span></NavLink>)}
   <div className="nav-divider"/><NavLink to="/mentor" onClick={()=>setMobile(false)} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon n="Bot"/><span>Research Mentor</span><span className="live-dot"/></NavLink></nav>
   <div className="sidebar-bottom"><div className="project-mini"><div className="mini-icon"><I.FolderKanban size={17}/></div><div className="min-w-0"><div className="tiny-label">ACTIVE PROJECT</div><div className="mini-title">Explainable AI...</div><div className="mini-progress"><span style={{width:'68%'}}/></div></div></div><div className="sidebar-user"><div className="avatar">R</div><div><b>Researcher</b><small>Student workspace</small></div><I.MoreHorizontal size={17}/></div></div>
  </aside>
  {mobile&&<div className="mobile-overlay" onClick={()=>setMobile(false)}/>} 
  <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)}><I.Menu/></button><div className="crumb"><span>ResearchMate</span><I.ChevronRight size={14}/><b>Research Workspace</b></div><div className="top-actions"><button className="icon-btn"><I.Bell size={18}/><span className="notif"/></button><div className="top-profile"><div className="avatar small">R</div><span>Researcher</span><I.ChevronDown size={15}/></div></div></header><div className="page">{children}</div></main>
 </div>
}
function PageHeader({eyebrow,title,desc,children}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{children&&<div className="header-actions">{children}</div>}</div>}
function StatCard({icon,value,label,trend}){return <div className="stat-card"><div className="stat-icon"><Icon n={icon}/></div><div className="stat-value">{value}</div><div className="stat-label">{label}</div>{trend&&<div className="stat-trend"><I.TrendingUp size={13}/>{trend}</div>}</div>}
function Dashboard(){const nav=useNavigate();return <>
 <PageHeader eyebrow="Research workspace" title="Good afternoon, Researcher" desc="Your research journey in one connected workspace."><Button onClick={()=>nav('/module/discovery')}><I.Plus size={17}/> New analysis</Button></PageHeader>
 <section className="hero-grid">
  <div className="project-card"><div className="project-head"><div><span className="status-pill"><span/> ACTIVE PROJECT</span><h2>{project.name}</h2><p>{project.stage}</p></div><div className="progress-ring" style={{'--p':`${project.progress*3.6}deg`}}><div><b>{project.progress}%</b><small>complete</small></div></div></div><div className="journey"><div className="journey-label"><b>Research journey</b><span>4 of 6 modules active</span></div><div className="journey-track">{modules.map((m,i)=><div key={m.id} className={`journey-step ${i<4?'done':''}`}><div className="journey-dot">{i<4?<I.Check size={12}/>:<span>{i+1}</span>}</div><small>{m.label.replace('Research ','').replace(' & Citations','')}</small></div>)}</div></div></div>
  <div className="mentor-card"><div className="mentor-orb"><I.Sparkles size={21}/></div><div className="mentor-copy"><span>AI MENTOR INSIGHT</span><h3>Your next best action</h3><p>Run the <b>Research Gap Finder</b> after reviewing your latest papers. This will help you lock the methodology with stronger evidence.</p><Button variant="secondary" onClick={()=>nav('/module/discovery')} >Open Discovery <I.ArrowRight size={15}/></Button></div></div>
 </section>
 <div className="stats-grid"><StatCard icon="BookOpen" value="42" label="Relevant papers" trend="8 new this week"/><StatCard icon="Target" value="84%" label="Novelty indicator" trend="Evidence-backed"/><StatCard icon="FileCheck2" value="72%" label="Paper readiness" trend="+12% this month"/><StatCard icon="CalendarDays" value="30d" label="Next deadline" trend="1 tracked CFP"/></div>
 <section className="section-head"><div><h2>Research modules</h2><p>Six focused workspaces combine the full research-to-publication workflow.</p></div><span className="module-count">6 MODULES · 30+ CAPABILITIES</span></section>
 <div className="module-grid">{modules.map((m,i)=><ModuleCard key={m.id} m={m} index={i}/>)}</div>
 <section className="bottom-grid"><div className="activity-card"><div className="card-title"><div><h3>Recent research activity</h3><p>Latest actions across your project</p></div><Button variant="secondary">View all</Button></div><Activity icon="Search" title="Semantic literature search" text="8 relevant papers added" time="12 min ago"/><Activity icon="ShieldCheck" title="Originality scan" text="Similarity analysis ready" time="Yesterday"/><Activity icon="MessageSquareText" title="AI reviewer" text="3 revision priorities generated" time="2 days ago"/></div><div className="health-card"><div className="card-title"><div><h3>Research health</h3><p>Project readiness signals</p></div></div><Health label="Research direction" value="Strong" pct={84}/><Health label="Literature coverage" value="Good" pct={76}/><Health label="Originality risk" value="Low" pct={91}/><Health label="Publication readiness" value="Building" pct={64}/></div></section>
 </>}
function ModuleCard({m,index}){const nav=useNavigate();return <button className={`module-card module-${m.color}`} onClick={()=>nav(`/module/${m.id}`)}><div className="module-top"><div className="module-icon"><Icon n={m.icon} s={21}/></div><span className="module-index">0{index+1}</span></div><h3>{m.label}</h3><p>{m.desc}</p><div className="module-footer"><span>{m.steps.length} capabilities</span><I.ArrowUpRight size={16}/></div></button>}
function Activity({icon,title,text,time}){return <div className="activity-row"><div className="activity-icon"><Icon n={icon} size={17}/></div><div className="activity-copy"><b>{title}</b><span>{text}</span></div><time>{time}</time></div>}
function Health({label,value,pct}){return <div className="health-row"><div><span>{label}</span><b>{value}</b></div><div className="health-bar"><span style={{width:`${pct}%`}}/></div></div>}
function ModulePage(){const {id}=useParams();const m=modules.find(x=>x.id===id)||modules[0];const [selected,setSelected]=useState(0);const [running,setRunning]=useState(false);const [done,setDone]=useState(false);const [input,setInput]=useState('');const current=m.steps[selected];const run=()=>{setRunning(true);setDone(false);setTimeout(()=>{setRunning(false);setDone(true)},700)};return <>
 <PageHeader eyebrow={`Module 0${modules.indexOf(m)+1} · Research workflow`} title={m.label} desc={m.desc}><Button variant="secondary"><I.Settings2 size={16}/> Configure</Button><Button onClick={run}><I.Sparkles size={16}/> {running?'Analyzing...':'Run analysis'}</Button></PageHeader>
 <div className="module-layout"><aside className="module-nav card"><div className="module-nav-head"><div className={`module-icon large module-${m.color}`}><Icon n={m.icon} s={22}/></div><div><b>{m.label}</b><span>{m.steps.length} capabilities</span></div></div>{m.steps.map((s,i)=><button key={s} onClick={()=>{setSelected(i);setDone(false)}} className={`capability ${selected===i?'selected':''}`}><span className="cap-num">{String(i+1).padStart(2,'0')}</span><span>{s}</span>{selected===i&&<I.ChevronRight size={15}/>}</button>)}</aside>
 <section><div className="analysis-grid"><div className="card input-card"><div className="card-title"><div><div className="eyebrow">Selected capability</div><h3>{current}</h3></div><span className="context-badge"><I.Link2 size={13}/> Project context on</span></div><p className="helper">Use the shared project context so every analysis builds on your existing research.</p>{id==='originality'&&<div className="upload-zone"><I.FileUp size={25}/><b>Upload manuscript</b><span>PDF, DOCX · up to 20 MB</span><button>Choose file</button></div>}<textarea className="input" value={input} onChange={e=>setInput(e.target.value)} placeholder={id==='originality'?'Or paste a section of your manuscript here...':'Enter your research topic, question, paper text or project context...'}></textarea><div className="input-meta"><span>Evidence-aware analysis</span><span>Shared project memory</span><span>AI-assisted</span></div><Button onClick={run}><I.Zap size={16}/>{running?'Running analysis...':'Analyze '+current}</Button></div>
 <div className="card result-card"><div className="result-head"><div><div className="eyebrow">ResearchMate output</div><h3>{done?'Analysis complete':'Ready for analysis'}</h3></div><span className={`result-status ${done?'success':''}`}>{done?'READY':'WAITING'}</span></div>{done?<DemoResult id={id} capability={current}/>:<div className="empty-result"><div className="empty-orb"><Icon n={m.icon} s={27}/></div><h3>Your evidence-backed result appears here</h3><p>Run the capability to preview the production workflow. Results will later come from your FastAPI + academic data + RAG pipeline.</p><div className="result-placeholder"><span/><span/><span/></div></div>}</div></div>
 <div className="card workflow-card"><div className="card-title"><div><h3>How this fits your research journey</h3><p>Every module shares the same project context.</p></div></div><div className="workflow"><div><span>01</span><b>Use project context</b><small>Topics, papers, manuscript and prior results</small></div><I.ArrowRight/><div><span>02</span><b>Analyze evidence</b><small>AI + academic sources + project data</small></div><I.ArrowRight/><div><span>03</span><b>Save the decision</b><small>Keep an auditable research trail</small></div></div></div>
 </section></div></>}
function DemoResult({id,capability}){if(id==='originality')return <div className="originality-result"><div className="score-row"><div className="score-circle"><b>8.4%</b><small>similarity</small></div><div><h4>Low similarity risk</h4><p>Prototype indicator — not a certified plagiarism verdict.</p></div></div><div className="mini-stats"><div><b>91%</b><span>Originality indicator</span></div><div><b>4</b><span>Potential matches</span></div><div><b>2</b><span>Citation issues</span></div></div><div className="match-list"><b>Potentially matched passages</b><div><span className="match-line high"/><p>Methodology paragraph · semantic overlap with 2 sources</p></div><div><span className="match-line"/><p>Introduction claim · citation recommended</p></div></div></div>;return <div className="demo-result"><div className="insight-box"><div className="big-score">84<span>/100</span></div><div><b>Strong research signal</b><p>Evidence suggests this direction is promising. Validate the remaining gap before committing to methodology.</p></div></div><div className="result-items"><div><I.CheckCircle2/><span><b>Evidence confidence</b>91% based on available project context</span></div><div><I.Target/><span><b>Recommended action</b>Review 5 most relevant papers</span></div><div><I.BookOpen/><span><b>Next module</b>Literature Intelligence</span></div></div><button className="save-result"><I.Save size={15}/> Save to project</button></div>}
function Mentor(){const [messages,setMessages]=useState([{from:'ai',text:'Hi! I’m your ResearchMate Mentor. I can use your project context across discovery, literature, writing, originality, review and publication.'}]);const [q,setQ]=useState('');const send=()=>{if(!q.trim())return;const x=q.trim();setQ('');setMessages(v=>[...v,{from:'user',text:x},{from:'ai',text:'Based on your current research stage, I recommend strengthening the research gap with recent literature, then running an originality scan before you finalize the manuscript.'}])};return <><PageHeader eyebrow="Cross-project AI" title="Research Mentor" desc="Ask questions without losing the context of your research project."><span className="mentor-context"><span/> Project context active</span></PageHeader><div className="mentor-shell card"><div className="chat-top"><div className="mentor-orb"><I.Bot size={20}/></div><div><b>ResearchMate Mentor</b><span>AI research guidance · project-aware</span></div><button className="secondary"><I.SlidersHorizontal size={15}/> Context</button></div><div className="chat-body">{messages.map((m,i)=><div key={i} className={`message ${m.from}`}>{m.from==='ai'&&<div className="chat-avatar"><I.Sparkles size={15}/></div>}<div className="bubble">{m.text}</div></div>)}</div><div className="suggestions"><button onClick={()=>setQ('Is my topic sufficiently novel?')}>Is my topic sufficiently novel?</button><button onClick={()=>setQ('What should I improve before submission?')}>What should I improve?</button><button onClick={()=>setQ('Which publication venue fits my paper?')}>Which venue fits my paper?</button></div><div className="chat-input"><input className="input" placeholder="Ask ResearchMate about your research..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/><Button onClick={send}><I.Send size={16}/></Button></div></div></>}
function App(){return <Layout><Routes><Route path="/" element={<Dashboard/>}/><Route path="/module/:id" element={<ModulePage/>}/><Route path="/mentor" element={<Mentor/>}/></Routes></Layout>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
